name: Build under Ubuntu

on:
  pull_request:
    branches:
      - master
      - v1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
          cache: gradle

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Build project and run tests
        shell: bash
        run: ./gradlew build --stacktrace

      # See: https://github.com/marketplace/actions/junit-report-action
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2.8.4
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Upload code coverage report
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
          verbose: true
