name: Run integration tests

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: zulu
          cache: gradle

      - name: Pull config
        run: git submodule update --init --recursive

      - name: Build project and run tests
        shell: bash
        run: ./gradlew integrationTest --stacktrace
